"""initial schema

Revision ID: 693835be0e9e
Revises: 
Create Date: 2026-08-29 20:45:42.929359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '693835be0e9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.Text(), nullable=True),
    sa.Column('repository_source', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('registry_type', sa.String(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('transport', sa.String(), nullable=True),
    sa.Column('runtime_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('package_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('environment_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'version', 'registry_type', 'identifier', name='uq_versions_natural_key')
    )
    op.create_table('hashes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('source', sa.String(), server_default='registry', nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hashes_version_observed', 'hashes', ['version_id', 'observed_at'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mcphound_version', sa.String(), nullable=False),
    sa.Column('deep', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('owasp', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('scans')
    op.drop_index('ix_hashes_version_observed', table_name='hashes')
    op.drop_table('hashes')
    op.drop_table('versions')
    op.drop_table('servers')
    # ### end Alembic commands ###
